# Generated by Django 2.1.3 on 2019-08-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blemish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=10, verbose_name='缺陷名称')),
                ('b_state', models.SmallIntegerField(choices=[(0, '启用'), (1, '禁用')], verbose_name='缺陷状态')),
            ],
        ),
        migrations.CreateModel(
            name='BlemishTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_rank', models.CharField(max_length=10, verbose_name='缺陷级别')),
                ('b_rate', models.CharField(max_length=10, verbose_name='完好率')),
                ('b_time', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('b_describe', models.CharField(max_length=300, verbose_name='缺陷描述')),
                ('b_affirm_user', models.CharField(max_length=10, null=True, verbose_name='确认人')),
                ('b_blemish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blemish.Blemish', verbose_name='缺陷类型')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发现人')),
            ],
        ),
    ]
