# Generated by Django 2.1.3 on 2019-08-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('blemish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehebungTack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=10, verbose_name='消缺任务名称')),
                ('b_voucher', models.CharField(max_length=50, verbose_name='工作单据')),
                ('b_user', models.CharField(max_length=10, verbose_name='负责人')),
                ('b_issuer', models.CharField(max_length=10, verbose_name='发布人')),
                ('b_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('b_describe', models.CharField(max_length=200, verbose_name='任务描述')),
                ('b_remarks', models.CharField(max_length=200, verbose_name='备注')),
                ('b_state', models.SmallIntegerField(choices=[(0, '执行中'), (1, '已完成')], verbose_name='消缺任务状态')),
                ('b_completion_time', models.DateTimeField(default=None, verbose_name='消缺任务完成时间')),
                ('b_blemish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blemish.BlemishTask', verbose_name='缺陷任务')),
                ('b_staff', models.ManyToManyField(to='user.User', verbose_name='消缺员')),
            ],
        ),
    ]
